version: '3.6'
services:
  web:
    build: 
      context: .
      dockerfile: docker/rails/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    volumes:
      - ".:/myapp"
