version: '3.6'
services:
  web:
    build: 
      context: .
      dockerfile: docker/rails/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    volumes:
      - ".:/myapp"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/volume:/var/lib/mysql
volumes:
  mysql-data: